### ISSUE TITLE
Acceso Admin onthego cencosud

### ISSUE THREAD

**Issue by dparada** [Moblox/onthego-tickets#10]
Hola,

intentamos ingresar al admin de Cencosud para comenzar a hacer pruebas y cargar informacion, pero no carga la página, adjunto imagen.

![cenco](https://cloud.githubusercontent.com/assets/11413721/6667145/e0868700-cbc8-11e4-8146-54eb50a2101c.jpg)

**Comment by acedward** [comment]
Aún no tenemos todo los módulos para un demo (imitar efup)

![image](https://cloud.githubusercontent.com/assets/3951895/6683105/498f44a2-cc60-11e4-8934-3345b2511997.png)

Noticias/Reconocimiento/Cursos/Beneficios/Recursos

Apenas tengamos Noticias vamos a liberarlo para revisión interna.

**Comment by acedward** [comment]
se creó rfup.*
