### ISSUE TITLE
Cargar curso

### ISSUE THREAD

**Issue by dparada** [Moblox/onthego-tickets#3]
Estimado,

Tenemos un problema al intentar cargar contenido flash a un curso, al cargar el zip nos da un error. Esto lo realizamos en la pestaña de capacitación, pinchando el nombre del curso y seleccionando el tipo storyline, si estamos realizado algún paso incorrecto favor indiquenos. Adjunto print.

![onthego3](https://cloud.githubusercontent.com/assets/11413721/6584548/ddba723e-c74a-11e4-9d7b-fe87c5171a47.jpg)
![onthego2](https://cloud.githubusercontent.com/assets/11413721/6584547/ddaa29ce-c74a-11e4-80fd-f9fc69cfe99f.jpg)
![onthego](https://cloud.githubusercontent.com/assets/11413721/6584494/97629802-c74a-11e4-93e6-258e82b2446f.jpg)

Detalle de error:   http://s3.amazonaws.com/capacitatech_tottus/

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3A868256281C813D</RequestId>
<HostId>
LCNCKdo5C0U1qL/fGes8LQAXuuX8HveM/Uz2wnKiqORjfMqTkAVsNas70VUxLC8sbnae6Etog9g=
</HostId>
</Error>

**Comment by acedward** [comment]
Daniela, por favor enviar archivo.
Así podemos hacer las pruebas y subirlo!
